'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class paidiatriko2
    
    '''<summary>
    '''DivNav control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivNav As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''TableHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableHeader As Global.System.Web.UI.WebControls.Table
    
    '''<summary>
    '''HyperLinkView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HyperLinkView As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''GridView1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridView1 As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''pi0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pi0 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''pi1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pi1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''pi2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pi2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''pi3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pi3 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''pi4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pi4 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''pi5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pi5 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ToolkitScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ToolkitScriptManager1 As Global.AjaxControlToolkit.ToolkitScriptManager
    
    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''UpdateProgress4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdateProgress4 As Global.System.Web.UI.UpdateProgress
    
    '''<summary>
    '''TextBox35 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox35 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TextBox1_CalendarExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox1_CalendarExtender As Global.AjaxControlToolkit.CalendarExtender
    
    '''<summary>
    '''TextBox36 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox36 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TextBox37 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox37 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TextBox38 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox38 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TextBox39 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox39 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''CheckBox1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBox1 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''CheckBox2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBox2 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''CheckBox3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBox3 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''CheckBox4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBox4 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''CheckBox5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBox5 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''CheckBox6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBox6 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''CheckBox7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBox7 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''CheckBox8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBox8 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''CheckBox9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBox9 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''TextBox40 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox40 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TextBox41 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox41 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TextBox42 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox42 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TextBox43 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox43 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TextBox44 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox44 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TextBox45 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox45 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TextBox46 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox46 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''CheckBox10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBox10 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''CheckBox11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBox11 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''CheckBox12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBox12 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''CheckBox13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBox13 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''CheckBox14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBox14 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''CheckBox15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBox15 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''CheckBox16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBox16 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''CheckBox17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBox17 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''CheckBox18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBox18 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''CheckBox19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBox19 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''CheckBox20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBox20 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''TextBox47 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox47 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TextBox48 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox48 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''CheckBox21 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBox21 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''oksygono control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents oksygono As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''TextBox49 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox49 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''CheckBox22 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBox22 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''thermo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents thermo As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''TextBox50 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox50 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TextBox51 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox51 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''CheckBox23 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBox23 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''loimo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loimo As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''TextBox52 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox52 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''CheckBox24 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBox24 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''spasmoi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spasmoi As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''TextBox53 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox53 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''CheckBox25 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBox25 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''ikteros control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ikteros As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''TextBox54 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox54 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TextBox55 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox55 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TextBox56 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox56 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TextBox57 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox57 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''CheckBox26 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBox26 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''CheckBox27 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBox27 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''CheckBox28 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBox28 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''CheckBox29 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBox29 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''DropDownListOmada control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DropDownListOmada As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''DropDownListPD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DropDownListPD As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''TextBox58 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox58 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TextBox59 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox59 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TextBox60 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox60 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TextBox61 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox61 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TextBox62 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox62 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TextBox63 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox63 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TextBox64 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox64 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TextBox1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TextBox65 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox65 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TextBox66 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox66 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TextBox67 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox67 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TextBox68 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox68 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TextBox69 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox69 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TextBox70 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox70 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TextBox71 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox71 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TextBox72 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox72 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TextBox73 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox73 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TextBox74 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox74 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TextBox75 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox75 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TextBox76 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox76 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TextBox77 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox77 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TextBox78 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox78 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TextBox79 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox79 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TextBox80 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox80 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Panel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel1 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''Button1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button1 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TableFooter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableFooter As Global.System.Web.UI.WebControls.Table
End Class
